# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bdellaro <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/23 14:39:37 by bdellaro          #+#    #+#              #
#    Updated: 2024/04/30 11:59:58 by bdellaro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME =		libft.a

SRC =		ft_atoi.c	\
		ft_bzero.c	\
		ft_isalnum.c	\
		ft_isalpha.c	\
		ft_isascii.c	\
		ft_isdigit.c	\
		ft_isprint.c	\
		ft_memchr.c	\
		ft_memcmp.c	\
		ft_memcpy.c	\
		ft_memmove.c	\
		ft_memset.c	\
		ft_strchr.c	\
		ft_strdup.c	\
		ft_strlcat.c	\
		ft_strlcpy.c	\
		ft_strlen.c	\
		ft_strncmp.c	\
		ft_strnstr.c	\
		ft_strrchr.c	\
		ft_tolower.c	\
		ft_toupper.c	\
		ft_calloc.c	\
		ft_substr.c	\
		ft_strjoin.c	\
		ft_putchar_fd.c	\
		ft_putnbr_fd.c	\
		ft_putstr_fd.c	\
		ft_putendl_fd.c	\
		ft_strmapi.c	\
		ft_striteri.c	\
		ft_strmapi.c	\
		ft_strtrim.c	\
		ft_itoa.c	\
		ft_split.c	\
		ft_lstadd_back.c	\
		ft_lstadd_front.c	\
		ft_lstclear.c		\
		ft_lstdelone.c		\
		ft_lstiter.c		\
		ft_lstlast.c		\
		ft_lstmap.c		\
		ft_lstnew.c		\
		ft_lstsize.c		\
		ft_free_array.c		\
		ft_utils.c		\
		ft_atol.c		\
		ft_printf/ft_print_char.c	\
		ft_printf/ft_printf.c		\
		ft_printf/ft_print_hexa.c	\
		ft_printf/ft_print_nbr.c	\
		ft_printf/ft_print_percent.c	\
		ft_printf/ft_print_ptr.c	\
		ft_printf/ft_print_str.c	\
		ft_printf/ft_print_unsigned.c	\
		get_next_line/get_next_line.c	\
		get_next_line/get_next_line_utils.c	\

OBJS =		$(SRC:.c=.o)

CC = 		gcc

CFLAGS =	-Wall -Wextra -Werror -I../include/

RM = 		rm -f

AR =		ar crs

all:		$(NAME)

$(NAME): 	$(OBJS)
	$(AR) $(NAME) $(OBJS)

clean:
	$(RM) $(OBJS)

fclean:		clean
	$(RM) $(NAME)

re:		fclean all

.PHONY:	all clean fclean re
